/**
 * kiwi-paper HTML template
 * Light/dark/auto theme, sticky TOC, mobile responsive, Korean typography
 */

/**
 * @param {object} opts
 * @param {string} opts.title
 * @param {string} opts.bodyHtml
 * @param {Array<{id: string, text: string, level: number}>} opts.headings
 * @param {{prev?: {href: string, title: string}, next?: {href: string, title: string}, index?: string}} [opts.navigation]
 * @param {string} [opts.katexCss]
 * @param {string} [opts.shikiCss]
 * @param {boolean} [opts.showToc]
 * @returns {string}
 */
export function renderPage({
  title,
  bodyHtml,
  headings = [],
  navigation = {},
  katexCss = '',
  shikiCss = '',
  showToc = true,
}) {
  const tocHtml = showToc && headings.length > 0 ? buildToc(headings) : '';
  const navHtml = buildNavigation(navigation);
  const hasToc = tocHtml.length > 0;

  return `<!DOCTYPE html>
<html lang="ko" data-theme="auto">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css">
${katexCss ? `<style>${katexCss}</style>` : ''}
${shikiCss ? `<style>${shikiCss}</style>` : ''}
<style>${getStyles(hasToc)}</style>
</head>
<body>
${hasToc ? `
<button class="toc-toggle" aria-label="목차 열기" aria-expanded="false">
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="15" y2="12"/><line x1="3" y1="18" x2="18" y2="18"/></svg>
</button>
<div class="toc-overlay" aria-hidden="true"></div>
<aside class="toc-sidebar" role="navigation" aria-label="목차">
  <div class="toc-header">
    <span class="toc-title">목차</span>
    <button class="toc-close" aria-label="목차 닫기">&times;</button>
  </div>
  <nav class="toc-nav">${tocHtml}</nav>
</aside>
` : ''}
<main class="content${hasToc ? '' : ' no-toc'}">
  <article class="article">
    ${bodyHtml}
  </article>
  ${navHtml}
  <footer class="footer">
    <p>Generated by <a href="https://github.com/hletrd/kiwi-paper">kiwi-paper</a></p>
  </footer>
</main>
<div class="theme-switcher">
  <button class="theme-btn" data-theme="light" aria-label="라이트 모드" title="라이트 모드">
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>
  </button>
  <button class="theme-btn" data-theme="auto" aria-label="시스템 설정" title="시스템 설정">
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>
  </button>
  <button class="theme-btn" data-theme="dark" aria-label="다크 모드" title="다크 모드">
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>
  </button>
</div>
${hasToc ? `<script>${getTocScript()}</script>` : ''}
<script>${getThemeScript()}</script>
</body>
</html>`;
}

/**
 * Render an index page listing multiple documents.
 */
export function renderIndexPage({ title, documents, katexCss = '', shikiCss = '' }) {
  const listHtml = documents
    .map(
      (d) =>
        `<li class="doc-item"><a href="${escapeHtml(d.href)}">${escapeHtml(d.title)}</a>${d.description ? `<p class="doc-desc">${escapeHtml(d.description)}</p>` : ''}</li>`,
    )
    .join('\n');

  const bodyHtml = `
<h1>${escapeHtml(title)}</h1>
<ul class="doc-list">${listHtml}</ul>`;

  return renderPage({
    title,
    bodyHtml,
    headings: [],
    showToc: false,
    katexCss,
    shikiCss,
  });
}

function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildToc(headings) {
  const minLevel = Math.min(...headings.map((h) => h.level));
  return `<ul class="toc-list">${headings
    .map(
      (h) =>
        `<li class="toc-item toc-level-${h.level - minLevel}"><a href="#${escapeHtml(h.id)}">${escapeHtml(h.text)}</a></li>`,
    )
    .join('')}</ul>`;
}

function buildNavigation(nav) {
  if (!nav || (!nav.prev && !nav.next && !nav.index)) return '';
  const parts = [];
  if (nav.prev) parts.push(`<a class="nav-prev" href="${escapeHtml(nav.prev.href)}">&larr; ${escapeHtml(nav.prev.title)}</a>`);
  if (nav.index) parts.push(`<a class="nav-index" href="${escapeHtml(nav.index)}">목록</a>`);
  if (nav.next) parts.push(`<a class="nav-next" href="${escapeHtml(nav.next.href)}">${escapeHtml(nav.next.title)} &rarr;</a>`);
  return `<nav class="page-nav">${parts.join('')}</nav>`;
}

function getStyles(hasToc) {
  return `
/* === Reset & Base === */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
  /* Light theme (default) */
  --bg: #ffffff;
  --bg-secondary: #f8f9fa;
  --bg-code: #f5f5f5;
  --text: #1a1a2e;
  --text-secondary: #4a4a6a;
  --text-muted: #8888a0;
  --border: #e2e2e8;
  --link: #2563eb;
  --link-hover: #1d4ed8;
  --accent: #6366f1;
  --toc-active: #6366f1;
  --toc-bg: #ffffff;
  --toc-hover: #f0f0f5;
  --nav-bg: #f8f9fa;
  --shadow: rgba(0,0,0,0.08);
  --del-color: #9ca3af;
  --table-stripe: #f8f9fb;
  --blockquote-border: #6366f1;
  --blockquote-bg: #f0f0ff;
  --kbd-bg: #eee;
  --mark-bg: #fef08a;
  --footnote-bg: #f9f9fb;
}

[data-theme="dark"] {
  /* Tokyo Night inspired dark */
  --bg: #1a1b26;
  --bg-secondary: #1f2030;
  --bg-code: #24283b;
  --text: #c0caf5;
  --text-secondary: #9aa5ce;
  --text-muted: #565f89;
  --border: #2f3349;
  --link: #7aa2f7;
  --link-hover: #89b4fa;
  --accent: #bb9af7;
  --toc-active: #bb9af7;
  --toc-bg: #1f2030;
  --toc-hover: #24283b;
  --nav-bg: #1f2030;
  --shadow: rgba(0,0,0,0.3);
  --del-color: #565f89;
  --table-stripe: #1f2030;
  --blockquote-border: #bb9af7;
  --blockquote-bg: #1f2035;
  --kbd-bg: #2f3349;
  --mark-bg: #e0af68;
  --footnote-bg: #1f2030;
}

@media (prefers-color-scheme: dark) {
  [data-theme="auto"] {
    --bg: #1a1b26;
    --bg-secondary: #1f2030;
    --bg-code: #24283b;
    --text: #c0caf5;
    --text-secondary: #9aa5ce;
    --text-muted: #565f89;
    --border: #2f3349;
    --link: #7aa2f7;
    --link-hover: #89b4fa;
    --accent: #bb9af7;
    --toc-active: #bb9af7;
    --toc-bg: #1f2030;
    --toc-hover: #24283b;
    --nav-bg: #1f2030;
    --shadow: rgba(0,0,0,0.3);
    --del-color: #565f89;
    --table-stripe: #1f2030;
    --blockquote-border: #bb9af7;
    --blockquote-bg: #1f2035;
    --kbd-bg: #2f3349;
    --mark-bg: #e0af68;
    --footnote-bg: #1f2030;
  }
}

html {
  font-size: 16px;
  scroll-behavior: smooth;
  -webkit-text-size-adjust: 100%;
}

body {
  font-family: 'Pretendard Variable', Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.8;
  word-break: keep-all;
  overflow-wrap: break-word;
  transition: background 0.25s ease, color 0.25s ease;
  ${hasToc ? 'display: grid; grid-template-columns: 1fr 260px; max-width: 1200px;' : 'max-width: 860px;'}
  margin: 0 auto;
  min-height: 100vh;
}

/* === Content === */
.content {
  padding: 2rem 2.5rem 4rem;
  min-width: 0;
}
.content.no-toc { padding: 2rem 3rem 4rem; }

.article { max-width: 100%; }

/* === Typography === */
h1, h2, h3, h4, h5, h6 {
  color: var(--text);
  font-weight: 700;
  line-height: 1.35;
  margin-top: 2em;
  margin-bottom: 0.6em;
  scroll-margin-top: 1rem;
}
h1 { font-size: 2rem; margin-top: 0; padding-bottom: 0.4em; border-bottom: 2px solid var(--border); }
h2 { font-size: 1.5rem; padding-bottom: 0.3em; border-bottom: 1px solid var(--border); }
h3 { font-size: 1.25rem; }
h4 { font-size: 1.1rem; }
h5, h6 { font-size: 1rem; color: var(--text-secondary); }

p { margin: 0.8em 0; }
a { color: var(--link); text-decoration: none; transition: color 0.15s; }
a:hover { color: var(--link-hover); text-decoration: underline; }

strong { font-weight: 700; }
em { font-style: italic; }
del { color: var(--del-color); text-decoration: line-through; }
mark { background: var(--mark-bg); padding: 0.1em 0.25em; border-radius: 3px; }

hr {
  border: none;
  height: 1px;
  background: var(--border);
  margin: 2.5em 0;
}

/* === Lists === */
ul, ol { padding-left: 1.6em; margin: 0.6em 0; }
li { margin: 0.3em 0; }
li > ul, li > ol { margin: 0.2em 0; }

/* === Blockquote === */
blockquote {
  border-left: 4px solid var(--blockquote-border);
  background: var(--blockquote-bg);
  padding: 1em 1.2em;
  margin: 1em 0;
  border-radius: 0 8px 8px 0;
  color: var(--text-secondary);
}
blockquote p { margin: 0.4em 0; }

/* === Code === */
code {
  font-family: 'JetBrains Mono', 'Fira Code', Menlo, Consolas, monospace;
  font-size: 0.875em;
  background: var(--bg-code);
  padding: 0.15em 0.4em;
  border-radius: 4px;
}

pre {
  background: var(--bg-code);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1em 1.2em;
  overflow-x: auto;
  margin: 1em 0;
  line-height: 1.6;
}
pre code {
  background: none;
  padding: 0;
  font-size: 0.85em;
}

/* Shiki dual theme */
pre.shiki { border: 1px solid var(--border); }
.shiki-light { display: block; }
.shiki-dark { display: none; }
[data-theme="dark"] .shiki-light { display: none; }
[data-theme="dark"] .shiki-dark { display: block; }
@media (prefers-color-scheme: dark) {
  [data-theme="auto"] .shiki-light { display: none; }
  [data-theme="auto"] .shiki-dark { display: block; }
}

/* === Tables === */
table {
  border-collapse: collapse;
  width: 100%;
  margin: 1em 0;
  font-size: 0.92em;
  overflow-x: auto;
  display: block;
}
thead { border-bottom: 2px solid var(--border); }
th, td {
  padding: 0.6em 1em;
  text-align: left;
  border: 1px solid var(--border);
}
th { background: var(--bg-secondary); font-weight: 600; }
tbody tr:nth-child(even) { background: var(--table-stripe); }

/* === Footnotes === */
section.footnotes {
  margin-top: 3em;
  padding-top: 1.5em;
  border-top: 1px solid var(--border);
  font-size: 0.88em;
  color: var(--text-secondary);
}
section.footnotes ol { padding-left: 1.4em; }
section.footnotes li { margin: 0.5em 0; }
.footnote-ref { font-size: 0.78em; vertical-align: super; }
.footnote-backref { text-decoration: none; margin-left: 0.3em; }

/* === KaTeX === */
.katex-display { overflow-x: auto; overflow-y: hidden; padding: 0.5em 0; }

/* === Images === */
img {
  max-width: 100%;
  height: auto;
  border-radius: 8px;
  margin: 1em 0;
}

/* === TOC Sidebar === */
.toc-sidebar {
  position: sticky;
  top: 0;
  height: 100vh;
  overflow-y: auto;
  padding: 1.5rem 1rem;
  border-left: 1px solid var(--border);
  background: var(--toc-bg);
  font-size: 0.85em;
  scrollbar-width: thin;
  scrollbar-color: var(--border) transparent;
}
.toc-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1em;
}
.toc-title {
  font-weight: 700;
  font-size: 0.95em;
  color: var(--text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}
.toc-close {
  display: none;
  background: none;
  border: none;
  font-size: 1.5em;
  cursor: pointer;
  color: var(--text-secondary);
}
.toc-nav {}
.toc-list {
  list-style: none;
  padding: 0;
  margin: 0;
}
.toc-item { margin: 0; }
.toc-item a {
  display: block;
  padding: 0.3em 0.6em;
  color: var(--text-secondary);
  border-radius: 4px;
  border-left: 2px solid transparent;
  transition: all 0.15s;
  text-decoration: none;
  line-height: 1.5;
}
.toc-item a:hover { background: var(--toc-hover); color: var(--text); }
.toc-item.active > a {
  color: var(--toc-active);
  border-left-color: var(--toc-active);
  font-weight: 600;
  background: var(--toc-hover);
}
.toc-level-1 a { padding-left: 1.4em; font-size: 0.92em; }
.toc-level-2 a { padding-left: 2.2em; font-size: 0.88em; }
.toc-level-3 a { padding-left: 3em; font-size: 0.85em; }

/* === TOC Toggle (mobile) === */
.toc-toggle {
  display: none;
  position: fixed;
  bottom: 1.5rem;
  right: 1.5rem;
  z-index: 1001;
  width: 48px;
  height: 48px;
  border-radius: 50%;
  border: 1px solid var(--border);
  background: var(--bg);
  color: var(--text);
  box-shadow: 0 2px 12px var(--shadow);
  cursor: pointer;
  align-items: center;
  justify-content: center;
}
.toc-overlay {
  display: none;
  position: fixed;
  inset: 0;
  z-index: 998;
  background: rgba(0,0,0,0.4);
}

/* === Navigation === */
.page-nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1em;
  margin-top: 3em;
  padding: 1em 1.2em;
  background: var(--nav-bg);
  border-radius: 8px;
  border: 1px solid var(--border);
  font-size: 0.92em;
}
.nav-prev, .nav-next { flex: 1; }
.nav-next { text-align: right; }
.nav-index { flex: 0 0 auto; }

/* === Theme Switcher === */
.theme-switcher {
  position: fixed;
  top: 1rem;
  right: 1rem;
  display: flex;
  gap: 2px;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 3px;
  z-index: 100;
  box-shadow: 0 1px 6px var(--shadow);
}
.theme-btn {
  background: none;
  border: none;
  padding: 6px 8px;
  cursor: pointer;
  border-radius: 6px;
  color: var(--text-muted);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.15s;
}
.theme-btn:hover { color: var(--text); background: var(--bg); }
.theme-btn.active {
  color: var(--accent);
  background: var(--bg);
  box-shadow: 0 1px 3px var(--shadow);
}

/* === Footer === */
.footer {
  margin-top: 4em;
  padding-top: 1.5em;
  border-top: 1px solid var(--border);
  text-align: center;
  font-size: 0.82em;
  color: var(--text-muted);
}

/* === Index page === */
.doc-list {
  list-style: none;
  padding: 0;
}
.doc-item {
  margin: 0.5em 0;
  padding: 1em 1.2em;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: 8px;
  transition: box-shadow 0.15s;
}
.doc-item:hover { box-shadow: 0 2px 8px var(--shadow); }
.doc-item a { font-weight: 600; font-size: 1.05em; }
.doc-desc { margin-top: 0.3em; font-size: 0.9em; color: var(--text-secondary); }

/* === Mobile === */
@media (max-width: 900px) {
  body {
    display: block !important;
    max-width: 100%;
  }
  .content {
    padding: 1.5rem 1.2rem 4rem;
  }
  .toc-sidebar {
    position: fixed;
    top: 0;
    right: -300px;
    width: 280px;
    height: 100vh;
    z-index: 999;
    border-left: 1px solid var(--border);
    box-shadow: -4px 0 16px var(--shadow);
    transition: right 0.25s ease;
  }
  .toc-sidebar.open { right: 0; }
  .toc-toggle { display: flex; }
  .toc-close { display: block; }
  .toc-overlay.open { display: block; }

  .theme-switcher {
    top: auto;
    bottom: 1.5rem;
    right: 5rem;
  }

  h1 { font-size: 1.6rem; }
  h2 { font-size: 1.3rem; }
  table { font-size: 0.82em; }
}

/* === Print === */
@media print {
  body { display: block !important; max-width: 100%; color: #000; background: #fff; }
  .toc-sidebar, .toc-toggle, .theme-switcher, .toc-overlay { display: none !important; }
  .content { padding: 0; }
  a { color: #000; text-decoration: underline; }
  a[href]::after { content: " (" attr(href) ")"; font-size: 0.8em; color: #666; }
  pre { border: 1px solid #ccc; }
  .page-nav { display: none; }
  .footer { display: none; }
  h1, h2, h3 { break-after: avoid; }
  table, pre, blockquote { break-inside: avoid; }
}
`;
}

function getTocScript() {
  return `
(function() {
  var sidebar = document.querySelector('.toc-sidebar');
  var toggle = document.querySelector('.toc-toggle');
  var overlay = document.querySelector('.toc-overlay');
  var closeBtn = document.querySelector('.toc-close');
  if (!sidebar || !toggle) return;

  function openToc() {
    sidebar.classList.add('open');
    overlay.classList.add('open');
    toggle.setAttribute('aria-expanded', 'true');
  }
  function closeToc() {
    sidebar.classList.remove('open');
    overlay.classList.remove('open');
    toggle.setAttribute('aria-expanded', 'false');
  }
  toggle.addEventListener('click', function() {
    sidebar.classList.contains('open') ? closeToc() : openToc();
  });
  overlay.addEventListener('click', closeToc);
  if (closeBtn) closeBtn.addEventListener('click', closeToc);

  // Close on link click (mobile)
  sidebar.querySelectorAll('.toc-item a').forEach(function(a) {
    a.addEventListener('click', function() {
      if (window.innerWidth <= 900) closeToc();
    });
  });

  // IntersectionObserver for active section
  var items = document.querySelectorAll('.toc-item');
  var headingEls = [];
  items.forEach(function(item) {
    var href = item.querySelector('a').getAttribute('href');
    if (href && href.startsWith('#')) {
      var el = document.getElementById(href.slice(1));
      if (el) headingEls.push({ el: el, item: item });
    }
  });

  if (headingEls.length === 0) return;

  var currentActive = null;
  var observer = new IntersectionObserver(function(entries) {
    entries.forEach(function(entry) {
      if (entry.isIntersecting) {
        var match = headingEls.find(function(h) { return h.el === entry.target; });
        if (match) {
          if (currentActive) currentActive.classList.remove('active');
          match.item.classList.add('active');
          currentActive = match.item;
          // Scroll TOC to keep active item visible
          if (window.innerWidth > 900) {
            match.item.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
          }
        }
      }
    });
  }, { rootMargin: '-10% 0px -80% 0px', threshold: 0 });

  headingEls.forEach(function(h) { observer.observe(h.el); });
})();
`;
}

function getThemeScript() {
  return `
(function() {
  var root = document.documentElement;
  var buttons = document.querySelectorAll('.theme-btn');
  var stored = localStorage.getItem('kiwi-paper-theme') || 'auto';

  function setTheme(theme) {
    root.setAttribute('data-theme', theme);
    localStorage.setItem('kiwi-paper-theme', theme);
    buttons.forEach(function(b) {
      b.classList.toggle('active', b.getAttribute('data-theme') === theme);
    });
  }

  setTheme(stored);
  buttons.forEach(function(b) {
    b.addEventListener('click', function() {
      setTheme(b.getAttribute('data-theme'));
    });
  });
})();
`;
}
