/**
 * kiwi-paper HTML template — namu.wiki-styled rendering
 * Authentic namu.wiki Liberty skin styling with light/dark mode
 */

/**
 * @param {object} opts
 * @param {string} opts.title
 * @param {string} opts.bodyHtml
 * @param {Array<{id: string, text: string, level: number}>} opts.headings
 * @param {{prev?: {href: string, title: string}, next?: {href: string, title: string}, index?: string}} [opts.navigation]
 * @param {string} [opts.katexCss]
 * @param {string} [opts.shikiCss]
 * @param {boolean} [opts.showToc]
 * @returns {string}
 */
export function renderPage({
  title,
  bodyHtml,
  headings = [],
  navigation = {},
  katexCss = '',
  shikiCss = '',
  showToc = true,
}) {
  const tocHtml = showToc && headings.length > 0 ? buildToc(headings) : '';
  const navHtml = buildNavigation(navigation);

  return `<!DOCTYPE html>
<html lang="ko" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css">
${katexCss ? `<style>${katexCss}</style>` : ''}
${shikiCss ? `<style>${shikiCss}</style>` : ''}
<style>${getStyles()}</style>
</head>
<body>
<div class="wiki-wrapper">
  <div class="wiki-header">
    <div class="wiki-header-inner">
      <a class="wiki-logo" href="${navigation.index || '#'}">🥝 kiwi-paper</a>
      <div class="theme-switcher">
        <button class="theme-btn" data-theme="light" aria-label="라이트 모드" title="라이트 모드">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>
        </button>
        <button class="theme-btn" data-theme="dark" aria-label="다크 모드" title="다크 모드">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>
        </button>
      </div>
    </div>
  </div>

  <div class="wiki-content-header">
    <h1 class="wiki-title">${escapeHtml(title)}</h1>
  </div>

  <div class="wiki-content">
    <article class="wiki-article">
      ${tocHtml}
      ${bodyHtml}
    </article>
    ${navHtml}
  </div>

  <div class="wiki-footer">
    <p>Generated by <a href="https://github.com/hletrd/kiwi-paper">kiwi-paper</a></p>
  </div>
</div>

<button class="toc-fab" aria-label="목차" style="display:none">
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="15" y2="12"/><line x1="3" y1="18" x2="18" y2="18"/></svg>
</button>
<div class="toc-overlay" aria-hidden="true"></div>

<script>${getThemeScript()}</script>
${tocHtml ? `<script>${getTocScript()}</script>` : ''}
</body>
</html>`;
}

/**
 * Render an index page listing multiple documents.
 */
export function renderIndexPage({ title, documents, katexCss = '', shikiCss = '' }) {
  const listHtml = documents
    .map(
      (d) =>
        `<li class="doc-item"><a href="${escapeHtml(d.href)}">${escapeHtml(d.title)}</a>${d.description ? `<p class="doc-desc">${escapeHtml(d.description)}</p>` : ''}</li>`,
    )
    .join('\n');

  const bodyHtml = `<ul class="doc-list">${listHtml}</ul>`;

  return renderPage({
    title,
    bodyHtml,
    headings: [],
    showToc: false,
    katexCss,
    shikiCss,
  });
}

function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildToc(headings) {
  const minLevel = Math.min(...headings.map((h) => h.level));

  // Build numbered entries (namu.wiki style: 1., 1.1., 1.1.1.)
  const counters = [0, 0, 0, 0, 0, 0];
  const items = headings.map((h) => {
    const depth = h.level - minLevel;
    counters[depth]++;
    // Reset deeper counters
    for (let i = depth + 1; i < counters.length; i++) counters[i] = 0;
    // Build number string
    const num = counters.slice(0, depth + 1).join('.');
    return `<div class="toc-entry toc-depth-${depth}"><a href="#${escapeHtml(h.id)}"><span class="toc-num">${num}.</span> ${escapeHtml(h.text)}</a></div>`;
  });

  return `<div class="wiki-toc" id="toc">
  <div class="toc-title">목차</div>
  <div class="toc-body">${items.join('')}</div>
</div>`;
}

function buildNavigation(nav) {
  if (!nav || (!nav.prev && !nav.next && !nav.index)) return '';
  const parts = [];
  if (nav.prev) parts.push(`<a class="nav-prev" href="${escapeHtml(nav.prev.href)}">&larr; ${escapeHtml(nav.prev.title)}</a>`);
  if (nav.index) parts.push(`<a class="nav-index" href="${escapeHtml(nav.index)}">목록</a>`);
  if (nav.next) parts.push(`<a class="nav-next" href="${escapeHtml(nav.next.href)}">${escapeHtml(nav.next.title)} &rarr;</a>`);
  return `<nav class="page-nav">${parts.join('')}</nav>`;
}

function getStyles() {
  return `
/* ============================================================
   kiwi-paper — namu.wiki Liberty skin inspired theme
   ============================================================ */

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

/* --- CSS Custom Properties (Light — default) --- */
:root, [data-theme="light"] {
  --namu-brand: #00a495;
  --namu-brand-hover: #007a6e;

  --bg-page: #f5f5f5;
  --bg-content: #ffffff;
  --bg-header: #f5f8fa;
  --bg-code: #f5f8fa;
  --bg-blockquote: #eeeeee;
  --bg-toc-title: #f5f8fa;
  --bg-table-header: #f5f5f5;

  --text-primary: #373a3c;
  --text-muted: #6e7478;
  --text-del: gray;

  --border: #e1e8ed;
  --border-heading: #cccccc;
  --border-blockquote: #71bc6d;
  --border-footnote: #777777;

  --link-color: #0275d8;
  --link-external: #009900;
  --link-hover: #014c8c;

  --radius: 0.35rem;
  --shadow-category: 0.15rem 0.15rem 0 0 #cfdae2;
}

/* --- Dark Theme --- */
[data-theme="dark"] {
  --bg-page: #1a1a1a;
  --bg-content: #1e1e1e;
  --bg-header: #2d2f34;
  --bg-code: #2d2f34;
  --bg-blockquote: #2a2a2a;
  --bg-toc-title: #1f2023;
  --bg-table-header: #2d2f34;

  --text-primary: #dddddd;
  --text-muted: #999999;
  --text-del: #aaaaaa;

  --border: #444444;
  --border-heading: #555555;
  --border-blockquote: #666c75;
  --border-footnote: #666666;

  --link-color: #E69720;
  --link-external: #E69720;
  --link-hover: #b3771d;

  --shadow-category: 0.15rem 0.15rem 0 0 #333;
}

/* --- Base --- */
html { font-size: 15px; scroll-behavior: smooth; -webkit-text-size-adjust: 100%; }

body {
  font-family: 'Pretendard Variable', Pretendard, 'Noto Sans Korean', 'Noto Sans KR', 'Nanum Gothic', -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
  font-size: 0.95rem;
  background: var(--bg-page);
  color: var(--text-primary);
  line-height: 1.7;
  word-break: keep-all;
  overflow-wrap: break-word;
  transition: background 0.2s, color 0.2s;
}

/* --- Wiki Wrapper --- */
.wiki-wrapper {
  max-width: 900px;
  margin: 0 auto;
  background: var(--bg-content);
  min-height: 100vh;
  border-left: 1px solid var(--border);
  border-right: 1px solid var(--border);
}

/* --- Header Bar --- */
.wiki-header {
  background: var(--namu-brand);
  padding: 0;
}
.wiki-header-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.5rem 1rem;
}
.wiki-logo {
  color: #fff;
  font-weight: 700;
  font-size: 1.1rem;
  text-decoration: none;
}
.wiki-logo:hover { color: #fff; text-decoration: none; opacity: 0.9; }

/* --- Theme Switcher --- */
.theme-switcher { display: flex; gap: 4px; }
.theme-btn {
  background: rgba(255,255,255,0.15);
  border: none;
  padding: 5px 8px;
  cursor: pointer;
  border-radius: 4px;
  color: rgba(255,255,255,0.7);
  display: flex;
  align-items: center;
  transition: all 0.15s;
}
.theme-btn:hover { background: rgba(255,255,255,0.25); color: #fff; }
.theme-btn.active { background: rgba(255,255,255,0.3); color: #fff; }

/* --- Content Header (Title Bar) --- */
.wiki-content-header {
  border-bottom: 1px solid var(--border);
  background: var(--bg-header);
  padding: 0.8rem 1.2rem;
}
.wiki-title {
  font-size: 1.8rem;
  font-weight: 700;
  margin: 0;
  padding: 0;
  border: none;
  color: var(--text-primary);
}

/* --- Content Area --- */
.wiki-content {
  padding: 1.2rem 1.5rem 2rem;
}

/* --- Typography --- */
h1, h2, h3, h4, h5, h6 {
  font-weight: 700;
  color: var(--text-primary);
  margin-top: 10px;
  margin-bottom: 10px;
  padding-bottom: 5px;
  border-bottom: 1px solid var(--border-heading);
  scroll-margin-top: 1rem;
  line-height: 1.4;
}
/* In-article h1 is rarely used (title is outside), but style it */
.wiki-article h1 { font-size: 2.0rem; }
.wiki-article h2 { font-size: 1.8rem; }
.wiki-article h3 { font-size: 1.6rem; }
.wiki-article h4 { font-size: 1.5rem; }
.wiki-article h5 { font-size: 1.3rem; border-bottom: none; }
.wiki-article h6 { font-size: 1.1rem; border-bottom: none; }

p { margin: 0.6em 0; }

a { color: var(--link-color); text-decoration: none; transition: color 0.1s; }
a:hover { color: var(--link-hover); text-decoration: underline; }

/* External links get a subtle icon */
a[href^="http"]:not([href*="kiwi-paper"])::after {
  content: " ↗";
  font-size: 0.75em;
  color: var(--link-external);
  vertical-align: super;
}

strong { font-weight: 700; }
em { font-style: italic; }
del { color: var(--text-del); text-decoration: line-through; }
mark { background: #fef08a; padding: 0.1em 0.2em; border-radius: 2px; }

hr {
  border: none;
  height: 1px;
  background: var(--border);
  margin: 2em 0;
}

/* --- Lists --- */
ul, ol { padding-left: 1.5em; margin: 0.5em 0; }
li { margin: 0.25em 0; }
li > ul, li > ol { margin: 0.15em 0; }

/* --- Blockquotes (namu.wiki style: green left border) --- */
blockquote {
  border-left: 5px solid var(--border-blockquote);
  background: var(--bg-blockquote);
  padding: 0.8em 1em;
  margin: 0.8em 0;
  border-radius: 0 var(--radius) var(--radius) 0;
  color: var(--text-primary);
}
blockquote p { margin: 0.3em 0; }
blockquote blockquote { margin: 0.5em 0; }

/* --- Code --- */
code {
  font-family: 'JetBrains Mono', 'Fira Code', Menlo, Consolas, monospace;
  font-size: 0.88em;
  background: var(--bg-code);
  border: 1px solid var(--border);
  padding: 0.12em 0.35em;
  border-radius: var(--radius);
}

pre {
  background: var(--bg-code);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 0.8rem;
  overflow-x: auto;
  margin: 0.8em 0;
  line-height: 1.55;
}
pre code {
  background: none;
  border: none;
  padding: 0;
  font-size: 0.85em;
}

/* Shiki dual theme */
.shiki-light { display: block; }
.shiki-dark { display: none; }
[data-theme="dark"] .shiki-light { display: none; }
[data-theme="dark"] .shiki-dark { display: block; }
pre.shiki { border: 1px solid var(--border); border-radius: var(--radius); }

/* --- Tables (namu.wiki: tight cells, thin borders) --- */
table {
  border-collapse: collapse;
  width: auto;
  margin: 0.8em 0;
  font-size: 0.92em;
}
th, td {
  padding: 0.3rem 0.6rem;
  border: 1px solid #dddddd;
  text-align: left;
}
th {
  background: var(--bg-table-header);
  font-weight: 600;
}
[data-theme="dark"] th,
[data-theme="dark"] td { border-color: var(--border); }

/* Responsive table wrapper */
div:has(> table) { overflow-x: auto; }

/* --- TOC (namu.wiki box style) --- */
.wiki-toc {
  border: 1px solid var(--border);
  border-radius: var(--radius);
  margin: 1em 0 1.5em;
  overflow: hidden;
}
.toc-title {
  font-size: 1.1rem;
  font-weight: 700;
  padding: 0.5rem 1rem;
  background: var(--bg-toc-title);
  border-bottom: 1px solid var(--border);
}
.toc-body { padding: 0.6rem 1rem; }
.toc-entry { margin: 0.15em 0; }
.toc-entry a {
  color: var(--link-color);
  text-decoration: none;
  display: inline-block;
  padding: 0.1em 0;
  font-size: 0.9rem;
  transition: color 0.1s;
}
.toc-entry a:hover { text-decoration: underline; }
.toc-entry.active > a { font-weight: 700; color: var(--namu-brand); }
.toc-num { color: var(--namu-brand); font-weight: 600; }
.toc-depth-1 { padding-left: 1.2em; }
.toc-depth-2 { padding-left: 2.4em; }
.toc-depth-3 { padding-left: 3.6em; }
.toc-depth-4 { padding-left: 4.8em; }

/* --- Footnotes (namu.wiki: small text, top border) --- */
section.footnotes {
  margin-top: 2.5em;
  padding-top: 1em;
  border-top: 1px solid var(--border-footnote);
  font-size: 0.8em;
  line-height: 2em;
  color: var(--text-muted);
}
section.footnotes ol { padding-left: 1.5em; }
section.footnotes li { margin: 0.3em 0; }
.footnote-ref {
  font-size: 0.75em;
  vertical-align: super;
  line-height: 0;
}
.footnote-ref a { color: var(--namu-brand); }
.footnote-backref { text-decoration: none; margin-left: 0.3em; color: var(--namu-brand); }

/* --- KaTeX --- */
.katex-display { overflow-x: auto; overflow-y: hidden; padding: 0.4em 0; }

/* --- Images --- */
img { max-width: 100%; height: auto; margin: 0.5em 0; }

/* --- Navigation --- */
.page-nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1em;
  margin-top: 2.5em;
  padding: 0.8em 1em;
  background: var(--bg-header);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  font-size: 0.9em;
}
.nav-prev, .nav-next { flex: 1; }
.nav-next { text-align: right; }
.nav-index { flex: 0 0 auto; }

/* --- Footer --- */
.wiki-footer {
  border-top: 1px solid var(--border);
  background: var(--bg-header);
  padding: 0.8rem 1.2rem;
  text-align: center;
  font-size: 0.8em;
  color: var(--text-muted);
}

/* --- Index page (doc list) --- */
.doc-list { list-style: none; padding: 0; }
.doc-item {
  margin: 0.4em 0;
  padding: 0.8em 1em;
  border: 1px solid var(--border);
  border-radius: var(--radius);
  box-shadow: var(--shadow-category);
  transition: box-shadow 0.15s;
}
.doc-item:hover { box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
.doc-item a { font-weight: 600; font-size: 1rem; }
.doc-desc { margin-top: 0.2em; font-size: 0.88em; color: var(--text-muted); }

/* --- Mobile TOC FAB --- */
.toc-fab {
  position: fixed;
  bottom: 1.5rem;
  right: 1.5rem;
  z-index: 1001;
  width: 44px;
  height: 44px;
  border-radius: 50%;
  border: none;
  background: var(--namu-brand);
  color: #fff;
  box-shadow: 0 2px 10px rgba(0,0,0,0.25);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}
.toc-overlay {
  display: none;
  position: fixed;
  inset: 0;
  z-index: 998;
  background: rgba(0,0,0,0.4);
}
.toc-overlay.open { display: block; }

/* --- Mobile --- */
@media (max-width: 768px) {
  .wiki-wrapper { border: none; }
  .wiki-content { padding: 1rem; }
  .wiki-article h2 { font-size: 1.4rem; }
  .wiki-article h3 { font-size: 1.25rem; }
  table { font-size: 0.82em; }

  .toc-fab { display: flex !important; }

  .wiki-toc {
    position: fixed;
    top: 0;
    right: -300px;
    width: 280px;
    height: 100vh;
    z-index: 999;
    margin: 0;
    border-radius: 0;
    border: none;
    border-left: 1px solid var(--border);
    background: var(--bg-content);
    box-shadow: -4px 0 16px rgba(0,0,0,0.15);
    transition: right 0.25s ease;
    overflow-y: auto;
  }
  .wiki-toc.open { right: 0; }
}

/* --- Print --- */
@media print {
  body { background: #fff; color: #000; }
  .wiki-wrapper { border: none; max-width: 100%; }
  .wiki-header, .theme-switcher, .toc-fab, .toc-overlay, .page-nav, .wiki-footer { display: none !important; }
  .wiki-content-header { background: none; border: none; }
  .wiki-content { padding: 0; }
  a { color: #000; }
  a[href]::after { content: " (" attr(href) ")"; font-size: 0.75em; color: #666; }
  a[href^="http"]::after { content: " (" attr(href) ")"; }
  a[href^="#"]::after { content: ""; }
  h1, h2, h3 { break-after: avoid; }
  table, pre, blockquote { break-inside: avoid; }
  .wiki-toc { break-inside: avoid; }
}
`;
}

function getTocScript() {
  return `
(function() {
  var toc = document.querySelector('.wiki-toc');
  var fab = document.querySelector('.toc-fab');
  var overlay = document.querySelector('.toc-overlay');
  if (!toc || !fab) return;

  function openToc() { toc.classList.add('open'); overlay.classList.add('open'); }
  function closeToc() { toc.classList.remove('open'); overlay.classList.remove('open'); }

  fab.addEventListener('click', function() {
    toc.classList.contains('open') ? closeToc() : openToc();
  });
  overlay.addEventListener('click', closeToc);

  // Close on entry click (mobile)
  toc.querySelectorAll('.toc-entry a').forEach(function(a) {
    a.addEventListener('click', function() {
      if (window.innerWidth <= 768) closeToc();
    });
  });

  // IntersectionObserver for active section
  var entries = toc.querySelectorAll('.toc-entry');
  var observed = [];
  entries.forEach(function(entry) {
    var href = entry.querySelector('a').getAttribute('href');
    if (href && href.startsWith('#')) {
      var el = document.getElementById(href.slice(1));
      if (el) observed.push({ el: el, entry: entry });
    }
  });
  if (observed.length === 0) return;

  var current = null;
  var observer = new IntersectionObserver(function(items) {
    items.forEach(function(item) {
      if (item.isIntersecting) {
        var match = observed.find(function(o) { return o.el === item.target; });
        if (match) {
          if (current) current.classList.remove('active');
          match.entry.classList.add('active');
          current = match.entry;
        }
      }
    });
  }, { rootMargin: '-5% 0px -85% 0px', threshold: 0 });

  observed.forEach(function(o) { observer.observe(o.el); });
})();
`;
}

function getThemeScript() {
  return `
(function() {
  var root = document.documentElement;
  var buttons = document.querySelectorAll('.theme-btn');
  var stored = localStorage.getItem('kiwi-paper-theme');

  // Default to system preference
  if (!stored) {
    stored = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  }

  function setTheme(theme) {
    root.setAttribute('data-theme', theme);
    localStorage.setItem('kiwi-paper-theme', theme);
    buttons.forEach(function(b) {
      b.classList.toggle('active', b.getAttribute('data-theme') === theme);
    });
  }

  setTheme(stored);
  buttons.forEach(function(b) {
    b.addEventListener('click', function() {
      setTheme(b.getAttribute('data-theme'));
    });
  });

  // Listen for system theme changes
  window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', function(e) {
    if (!localStorage.getItem('kiwi-paper-theme')) {
      setTheme(e.matches ? 'dark' : 'light');
    }
  });
})();
`;
}
